spring.application.name: basestack

# Security config

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/HaithemRealm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

# JWT Config

jwt:
  auth:
    converter:
      resource-id: my-app-client
      principal-attribute: principal_username

logging:
  level:
    org.springframework.security: TRACE

server:
  port: 8081
